version: '3.4'

services:
  web_shop.restapi:
    image: ${DOCKER_REGISTRY-}webshoprestapi
    build:
      context: .
      dockerfile: Web_Shop.RestAPI/Dockerfile
    depends_on:
      - wwsi_shop_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - wwsi_shop_db

  wwsi_shop_db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - wwsi_shop_dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

volumes:
  wwsi_shop_dbdata:
